create table if not exists public.establecimientos_accesos (
  id bigint generated by default as identity primary key,
  email_normalizado text not null,
  scope_kind text not null default 'ESTABLECIMIENTO' check (scope_kind in ('GLOBAL', 'COMUNA', 'ESTABLECIMIENTO')),
  rbd text null references public.establecimientos(rbd) on delete cascade,
  comuna text null,
  descripcion text null,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint establecimientos_accesos_scope_target_check check (
    (scope_kind = 'GLOBAL' and rbd is null and comuna is null)
    or (scope_kind = 'COMUNA' and comuna is not null and rbd is null)
    or (scope_kind = 'ESTABLECIMIENTO' and rbd is not null)
  )
);

create index if not exists establecimientos_accesos_email_idx
  on public.establecimientos_accesos (email_normalizado, activo);

create unique index if not exists establecimientos_accesos_unique_scope_idx
  on public.establecimientos_accesos (email_normalizado, scope_kind, coalesce(rbd, ''), coalesce(comuna, ''));

create or replace function public.is_global_admin()
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  current_email text;
  has_match boolean;
  admin_roles_table_exists boolean;
begin
  current_email := public.normalize_portal_email(auth.jwt() ->> 'email');

  if current_email is null then
    return false;
  end if;

  select exists (
    select 1
    from public.admin_correos admins
    where admins.correo_electronico = current_email
  ) into has_match;

  if has_match then
    return true;
  end if;

  select exists (
    select 1
    from public.establecimientos_accesos accesos
    where accesos.activo = true
      and accesos.scope_kind = 'GLOBAL'
      and public.normalize_portal_email(accesos.email_normalizado) = current_email
  ) into has_match;

  if has_match then
    return true;
  end if;

  select to_regclass('public.admin_user_roles') is not null
  into admin_roles_table_exists;

  if not admin_roles_table_exists then
    return false;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_user_roles'
      and column_name = 'correo_electronico'
  ) then
    execute 'select exists (
      select 1
      from public.admin_user_roles roles
      where lower(trim(roles.correo_electronico)) = $1
    )'
    into has_match
    using current_email;

    if has_match then
      return true;
    end if;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_user_roles'
      and column_name = 'email'
  ) then
    execute 'select exists (
      select 1
      from public.admin_user_roles roles
      where lower(trim(roles.email)) = $1
    )'
    into has_match
    using current_email;

    if has_match then
      return true;
    end if;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'admin_user_roles'
      and column_name = 'correo'
  ) then
    execute 'select exists (
      select 1
      from public.admin_user_roles roles
      where lower(trim(roles.correo)) = $1
    )'
    into has_match
    using current_email;

    if has_match then
      return true;
    end if;
  end if;

  return false;
end;
$$;

create or replace function public.current_accessible_rbds()
returns table (rbd text)
language sql
stable
security definer
set search_path = public
as $$
  with current_identity as (
    select public.normalize_portal_email(auth.jwt() ->> 'email') as correo
  ),
  explicit_scopes as (
    select establecimientos.rbd
    from public.establecimientos_accesos accesos
    cross join current_identity
    join public.establecimientos establecimientos
      on accesos.scope_kind = 'GLOBAL'
    where accesos.activo = true
      and current_identity.correo is not null
      and public.normalize_portal_email(accesos.email_normalizado) = current_identity.correo

    union all

    select establecimientos.rbd
    from public.establecimientos_accesos accesos
    cross join current_identity
    join public.establecimientos establecimientos
      on accesos.scope_kind = 'COMUNA'
     and establecimientos.comuna = accesos.comuna
    where accesos.activo = true
      and current_identity.correo is not null
      and public.normalize_portal_email(accesos.email_normalizado) = current_identity.correo

    union all

    select accesos.rbd
    from public.establecimientos_accesos accesos
    cross join current_identity
    where accesos.activo = true
      and accesos.scope_kind = 'ESTABLECIMIENTO'
      and accesos.rbd is not null
      and current_identity.correo is not null
      and public.normalize_portal_email(accesos.email_normalizado) = current_identity.correo
  )
  select distinct scoped.school_rbd as rbd
  from (
    select profile.rbd as school_rbd
    from public.usuarios_perfiles profile
    where profile.id = auth.uid()
      and profile.rbd is not null

    union all

    select nullif(trim(base."RBD"), '') as school_rbd
    from public."BASE DE DATOS ESCUELAS SLEP" as base
    cross join current_identity
    where current_identity.correo is not null
      and public.normalize_portal_email(base."CORREO REPRESENTANTE") = current_identity.correo

    union all

    select explicit_scopes.rbd as school_rbd
    from explicit_scopes
  ) as scoped
  where scoped.school_rbd is not null;
$$;

create or replace function public.get_current_portal_scope()
returns table (
  role_text text,
  is_global_admin boolean,
  accessible_rbds text[],
  default_rbd text,
  can_select_school boolean,
  landing_route text
)
language sql
stable
security definer
set search_path = public
as $$
  with profile_row as (
    select rol
    from public.usuarios_perfiles
    where id = auth.uid()
    limit 1
  ),
  scope_rbds as (
    select coalesce(array_agg(scoped.rbd order by scoped.rbd), array[]::text[]) as rbds
    from public.current_accessible_rbds() scoped
  )
  select
    coalesce((select rol::text from profile_row), case when cardinality(scope_rbds.rbds) > 0 then 'ADMIN' else 'DIRECTOR' end) as role_text,
    public.is_global_admin() as is_global_admin,
    scope_rbds.rbds as accessible_rbds,
    case
      when public.is_global_admin() then null
      when cardinality(scope_rbds.rbds) = 1 then scope_rbds.rbds[1]
      else null
    end as default_rbd,
    (public.is_global_admin() or cardinality(scope_rbds.rbds) > 1) as can_select_school,
    case
      when public.is_global_admin() or cardinality(scope_rbds.rbds) > 1 then '/admin'
      else '/resumen'
    end as landing_route
  from scope_rbds;
$$;

create or replace function public.bootstrap_current_user_profile_from_base_escuelas()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_email         text;
  admin_record          record;
  representative_record record;
  matched_school        record;
  explicit_access_exists boolean;
  base_exists           boolean;
begin
  current_email := public.normalize_portal_email(auth.jwt() ->> 'email');

  if auth.uid() is null then
    raise exception 'No hay sesión autenticada para bootstrap de perfil.';
  end if;

  if current_email is null then
    raise exception 'No se pudo determinar el correo del usuario autenticado desde el token.';
  end if;

  select * into admin_record
  from public.admin_correos
  where correo_electronico = current_email
  limit 1;

  if found or public.is_global_admin() then
    insert into public.usuarios_perfiles (
      id, correo_electronico, rol, rbd, comuna, nombre_director
    )
    values (
      auth.uid(),
      current_email,
      'ADMIN',
      null,
      null,
      coalesce(admin_record.nombre, current_email)
    )
    on conflict (id) do update set
      correo_electronico = excluded.correo_electronico,
      rol               = 'ADMIN',
      rbd               = null,
      comuna            = null,
      nombre_director   = excluded.nombre_director,
      updated_at        = now();

    return;
  end if;

  select exists (
    select 1
    from public.establecimientos_accesos accesos
    where accesos.activo = true
      and public.normalize_portal_email(accesos.email_normalizado) = current_email
  ) into explicit_access_exists;

  if explicit_access_exists then
    insert into public.usuarios_perfiles (
      id, correo_electronico, rol, rbd, comuna, nombre_director
    )
    values (
      auth.uid(),
      current_email,
      'ADMIN',
      null,
      null,
      current_email
    )
    on conflict (id) do update set
      correo_electronico = excluded.correo_electronico,
      rol               = 'ADMIN',
      rbd               = null,
      comuna            = null,
      nombre_director   = excluded.nombre_director,
      updated_at        = now();

    return;
  end if;

  select exists (
    select 1 from information_schema.tables
    where table_schema = 'public'
      and table_name   = 'BASE DE DATOS ESCUELAS SLEP'
  ) into base_exists;

  if not base_exists then
    raise exception 'El correo % no está autorizado y la base de escuelas SLEP aún no fue cargada.', current_email;
  end if;

  select
    nullif(trim(base."REPRESENTANTE CONSEJO ESCOLAR"), '') as representante_nombre
  into representative_record
  from public."BASE DE DATOS ESCUELAS SLEP" as base
  where public.normalize_portal_email(base."CORREO REPRESENTANTE") = current_email
  order by nullif(trim(base."NOMBRE ESTABLECIMIENTO"), '') nulls last
  limit 1;

  if found then
    insert into public.usuarios_perfiles (
      id, correo_electronico, rol, rbd, comuna, nombre_director
    )
    values (
      auth.uid(),
      current_email,
      'ADMIN',
      null,
      null,
      coalesce(representative_record.representante_nombre, current_email)
    )
    on conflict (id) do update set
      correo_electronico = excluded.correo_electronico,
      rol               = 'ADMIN',
      rbd               = null,
      comuna            = null,
      nombre_director   = excluded.nombre_director,
      updated_at        = now();

    return;
  end if;

  perform public.sync_establecimientos_from_base_escuelas();

  select *
  into matched_school
  from public.base_escuelas_normalized_rows() as rows
  where rows.correo_electronico = current_email
  order by rows.rbd
  limit 1;

  if matched_school.rbd is null then
    raise exception 'No existe una escuela asociada al correo % en BASE DE DATOS ESCUELAS SLEP.', current_email;
  end if;

  insert into public.usuarios_perfiles (
    id, correo_electronico, rol, rbd, comuna, nombre_director
  )
  values (
    auth.uid(),
    current_email,
    'DIRECTOR',
    matched_school.rbd,
    matched_school.comuna,
    matched_school.director
  )
  on conflict (id) do update set
    correo_electronico = excluded.correo_electronico,
    rol               = 'DIRECTOR',
    rbd               = excluded.rbd,
    comuna            = excluded.comuna,
    nombre_director   = excluded.nombre_director,
    updated_at        = now();
end;
$$;